### ISSUE TITLE
question

### ISSUE THREAD

**Issue by sunshine-lh** [andru47/smkhe#10]
Hello, I ran your program, but found that the encrypted number cannot exceed 8192. What is the reason? I want to encrypt a number larger than 8192. Is there any solution? I look forward to your reply.

**Comment by andru47** [comment]
Hey @sunshine-lh! Could you paste the code that you are trying to execute? You can see [here](https://github.com/andru47/smkhe/blob/master/test/encryptor.cpp) in the test that you are able to encrypt 8192 numbers up to 10000, generated by `uniform_real_distribution`. Generally, if you want to encrypt bigger numbers, you must decrease the scale. In the test, the scale is `2^40`.

**Comment by sunshine-lh** [comment]
Hello, when I change 59 in this code to 55, Parameters parametersMKEval_me((1ULL << 59), 16384, PRIMES, SPECIAL_PRIMES);. I can successfully encrypt and decrypt large numbers and perform addition operations. However, when I multiply ciphertext and encoded plaintext, there are still problems. However, when I change 55 back to 59 again, the multiplication between the ciphertext with smaller numbers and the encoded plaintext can be successfully performed. This is rather troublesome. Do you have a solution to this problem?

**Comment by andru47** [comment]
The problem is that the scale is too big for those numbers. Try decreasing the scale to `1ULL << 40` or even `1ULL << 30`. @sunshine-lh

**Comment by sunshine-lh** [comment]
Hello, when I changed 1ULL<<59 to 1ULL<<30, the addition homomorphic operation of multi key homomorphic encryption can get correct results, but the multiplication homomorphic operation gets wrong results. Do I need to modify other parameters after modifying the scale?

**Comment by andru47** [comment]
The problem is that when you decrease the scale you also need to decrease the primes in the first vector. In this [test](https://github.com/andru47/smkhe/blob/master/test/evaluator.cpp), you would need to redefine the `PRIMES` vector in the following way:
- You can keep the first one as it is: this is used as a special prime and needs to be bigger than the scale
- The other ones need to be very close to the scale: in this example, the scale is `2^59` and those primes are close to it. The reason is: 
     - You encode a number and hence you 'store' it multiplied with a scale
     - You multiply two encoded numbers and hence the product is multiplied with a squared scale
     - Now, if you want to decode, the result would be invalid since you have `num * scale^2` instead of `num * scale`
     - So you need to somehow divide by `scale`: to do this you eliminate the last prime from the RNS base. Therefore, you need to have close-to-scale primes in the RNS base so the end result would approximately be `num * scale`

With this in mind, you need to generate your primes, since SMKHE does not do this as other libraries do. You can use some of the default parameters from [here](https://github.com/tuneinsight/lattigo/blob/master/ckks/params.go), depending on you scale or you can generate your own primes.

I also recommend reading some papers about CKKS so you can understand how it works -- you can use the papers from the README of this repo. @sunshine-lh

**Comment by sunshine-lh** [comment]
Thank you very much. I have solved my problem.

**Comment by taxuexunshang** [comment]
@sunshine-lh Hello, I have encountered the same problem as you. Now we have adjusted the parameters according to the lattigo library, but the homomorphic operation on larger values still fails to get the correct result. May I ask how you solved this problem?
